[colors.bright]
black = "0x002b36"
blue = "0x839496"
cyan = "0x93a1a1"
green = "0x586e75"
magenta = "0x6c71c4"
red = "0xcb4b16"
white = "0xfdf6e3"
yellow = "0x657b83"

[colors.normal]
black = "0x073642"
blue = "0x268bd2"
cyan = "0x2aa198"
green = "0x859900"
magenta = "0xd33682"
red = "0xdc322f"
white = "0xeee8d5"
yellow = "0xb58900"

[colors.primary]
background = "0xfdf6e3"
foreground = "0x586e75"

[font]
size = 20

[font.bold]
family = "UbuntuMono Nerd Font"
style = "regular"

[font.normal]
family = "UbuntuMono Nerd Font"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"

# Unbind Ctrl-Dash in favor of Ctrl-Shift-Dash, so that Tmux can take Ctrl-Dash
# as an typo-friendly alternate for Ctrl-Prefix Dash. This also matches the
# standard Chrome zoom shortcut.
[[keyboard.bindings]]
key = "-"
mods = "Control"
chars = "\u001f" # pass through Ctrl-Dash
[[keyboard.bindings]]
key = "_"
mods = "Control|Shift"
action = "DecreaseFontSize"
[[keyboard.bindings]]
key = "="
mods = "Control"
action = "None" # nothing needs this, and I'm not sure there's a correct byte
[[keyboard.bindings]]
key = "+"
mods = "Control|Shift"
action = "IncreaseFontSize"

[mouse]
hide_when_typing = true

[window]
decorations = "full"
option_as_alt = "Both"

[window.padding]
x = 3
y = 3
