theme = "solarized_light"

[editor.cursor-shape]
insert = "bar"

[editor.lsp]
display-messages = true

[keys.normal]
"x" = ["select_mode", "extend_line_below"]
"X" = ["select_mode", "extend_line_above"]
"esc" = ["keep_primary_selection", "collapse_selection"]
"C-c" = ["keep_primary_selection", "collapse_selection"]
"C-7" = "toggle_comments" # in Alacritty, this is how I map C-/
"L" = ["extend_to_line_end", "change_selection"]

[keys.select]
"x" = ["extend_line_below"]
"X" = ["extend_line_above"]
"esc" = ["normal_mode", "keep_primary_selection", "collapse_selection"]
"C-c" = ["normal_mode", "keep_primary_selection", "collapse_selection"]

[keys.select.g]
q = ":reflow"

[keys.insert]
"C-c" = "normal_mode"
